In [1]:
import pandas as pd

In [ ]:
data= {
    'a': [1,2,3],
    'b': [10,20,30],
}

df = pd.DataFrame(data)
df
# las laves representan las columnas
# los valores representan las filas

   a   b
0  1  10
1  2  20
2  3  30

In [7]:
type(df)

pandas.DataFrame

In [ ]:
#Aceder a una columna
#UNa columna es una serie de pandas
df['a']

0    1
1    2
2    3
Name: a, dtype: int64

CARGANDO DATOS CON PANDAS

In [11]:
df =pd.read_csv("datos_ventas.csv", sep =";")

In [12]:
df.head(10)

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
0,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,19/10/24,1500,1,1500
1,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,16/11/24,1500,2,3000
2,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,20/02/24,1000,2,2000
3,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,3/06/24,1000,3,3000
4,TIENDA01,Matriz,10003,Televisor,123456333,Jorge Mateus,1/02/24,3500,3,10500
5,TIENDA01,Matriz,10004,Lavadora,123456222,Maria Garcia,30/05/24,2400,1,2400
6,TIENDA01,Matriz,10005,Laptop,123456222,Maria Garcia,29/10/24,3000,3,9000
7,TIENDA01,Matriz,10005,Laptop,123456222,Maria Garcia,24/11/24,3000,2,6000
8,TIENDA01,Matriz,10007,Mezclador,123456222,Maria Garcia,14/05/24,200,1,200
9,TIENDA01,Matriz,10008,Cafetera,123456222,Maria Garcia,5/07/24,240,1,240

In [13]:
type(df )

pandas.DataFrame

In [15]:
type(df["Tienda"])

pandas.Series

In [18]:
df["Tienda"]

0     Matriz
1     Matriz
2     Matriz
3     Matriz
4     Matriz
5     Matriz
6     Matriz
7     Matriz
8     Matriz
9     Matriz
10    Matriz
11    Matriz
12    Matriz
13    Matriz
14    Matriz
15    Matriz
16    Matriz
17    Matriz
18    Matriz
19    Matriz
20    Matriz
21    Matriz
22    Matriz
23    Matriz
24    Matriz
25    Matriz
26    Matriz
27    Matriz
28    Matriz
29    Matriz
30    Matriz
31    Matriz
32    Matriz
Name: Tienda, dtype: str