2. Excel | pd.read_excel()
Uno de los tipos de archivo más utilizados para datos es el archivo de tipo Excel (.xlsx).

Dato importante: Para leer archivos en Excel con Pandas, es necesario tener instalada la biblioteca openpyxl. La distribución Anaconda trae esta biblioteca preinstalada, en caso de no usar Anaconda es necesario intalarla.
pip install openpyxl

In [1]:
import pandas as pd

In [3]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
df = pd.read_excel(io="datasets/DatosVentas.xlsx", sheet_name="datos_ventas")

In [5]:
df.head()

,CodigoTienda,Tienda,CodigoProducto,DescripcionProduto,Matricula,NombreVendedor,FechaDeVenta,PrecioUnitario,Cantidad,Valorventa
0,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,2024-10-19,1500,1,1500
1,TIENDA01,Matriz,10001,Smartphone,123456111,Jose Martinez,2024-11-16,1500,2,3000
2,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,2024-02-20,1000,2,2000
3,TIENDA01,Matriz,10002,Tablet,123456333,Jorge Mateus,2024-06-03,1000,3,3000
4,TIENDA01,Matriz,10003,Televisor,123456333,Jorge Mateus,2024-02-01,3500,3,10500

In [8]:
df1= pd.read_excel(io="datasets/DatosVentas.xlsx", sheet_name="funcionarios")

In [9]:
df1.head()

   Matricula NombreVendedor
0  123456111  Jose Martinez
1  123456333   Jorge Mateus
2  123456222   Maria García